const mockEvents = {
  city: {
    id: 1007698,
    city: 'Berlin',
    lat: 52.52,
    lon: 13.38,
    state: '',
    country: 'de',
    zip: 'meetup1',
    member_count: 2374
  },
  events: [
    {
      created: 1541410810000,
      duration: 7200000,
      id: 'jmwllqybccbkb',
      name: 'Silicon Allee Monthly Meetup',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1578384000000,
      local_date: '2020-01-07',
      local_time: '09:00',
      updated: 1575564259000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 26,
      venue: {
        id: 25726180,
        name: 'R/D Coffee Bar',
        lat: 52.53022766113281,
        lon: 13.384085655212402,
        repinned: true,
        address_1: 'Chausseestraße 19',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1511954195000,
        name: 'Silicon Allee Events',
        id: 26735498,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Silicon-Allee-Events',
        who: 'Members',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Silicon-Allee-Events/events/jmwllqybccbkb/',
      description: '<p>** Pls register via Eventbritre &gt;http://bit.ly/367jjOs</a></p> <p>New Year resolutions discussed (or excuses for breaking them) between networking. Our team look forward to meeting new arrivals, freelancers and anyone interested in connecting with Berlin’s startup ecosystem.</p> <p>Early stage founders are welcome to pitch our Berlin Founders Fund &gt; <a >http://bit.ly/SiliconAlleeBFF</a></p> <p>Drop by and share your festive stories and 2020 plans!</p> <p>//</p> <p>Silicon Allee\'s roots began in Berlin over 8 years ago, and since then we have evolved into a key stakeholder in the capital\'s startup scene. Our campus opened in 2017 and includes office rental, event space and studio apartments for short &amp; medium term rent. We look forward to seeing you at one of our monthly meetups, open events or even on campus at our public cafe &amp; bar. Be sure to contact &amp; drop by if you\'re in town!<br/>#BerlinStartups #Since2011</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1575894490000,
      duration: 7200000,
      id: '267060139',
      name: 'Berlin Pitch Bootcamp: Learn to Pitch Your Ideas Like a Pro!',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1581530400000,
      local_date: '2020-02-12',
      local_time: '19:00',
      updated: 1575894490000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 10,
      venue: {
        id: 25182824,
        name: 'Ahoy! Berlin - Coworking & Innovation',
        lat: 52.54090881347656,
        lon: 13.39048957824707,
        repinned: true,
        address_1: 'Wattstraße 11',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1370652692000,
        name: 'Berlin Startup Founder 101',
        id: 8831882,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Berlin-Startup-Founder-101',
        who: 'Aspiring Founders',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Berlin-Startup-Founder-101/events/267060139/',
      description: '<p>After a series of pure F-Impact pitching events, we want to gift you with a special pitching masterclass led by Dirk Lehmann, our favourite pitch trainer!</p> <p>Pitching your startup ideas effectively is a crucial skill that will help you acquire financing, customers, partners, and top talent.</p> <p>In just three hours, the Startup Pitch Bootcamp will help you improve your pitching skills and recruit potential co-founders. This intensive, collaborative workshop features talks by our favorite pitch trainer designed to help you understand the key ingredients of a successful pitch. Then, you can apply that learning and pitch to both experts and peers to receive constructive feedback in a relaxed setting.</p> <p>Join us for a fun evening, with Dirk Lehmann - Pitch Coach &amp; Innovation Advisor. If you want to take a sneak peak to see what Dirk can do for you above and beyond the content of this session, please check out <a training.de</a>.</p> <p>&gt;&gt; Who Should Attend the Pitch Bootcamp?<br/>- Anyone who needs practice and expert advice on pitching.<br/>- Anyone who has an idea for a startup or an early-stage company.<br/>- Anyone that is interested in joining a new startup or looking for a co-founder.</p> <p>&gt;&gt; &gt;&gt; This event is FREE, but space is quite limited and that\'s why you need to register over here: <a >https://fi.co/e/216401/meetup</a></p> <p>We are glad to be hosted by Ahoy for this bootcamp!<br/>Ahoy! Berlin is a flexible workspace where companies and individuals can rent fully equipped offices, conference rooms and work desks under flexible terms in a unique environment. We serve to help budding startups and freelancers steer clear of potential pitfalls by connecting them to a wider community of possible collaborators and investors via Tech Berlin sister companies Openers and Tech Open Air, while also offering additional services like event management and legal advice.<br/>---</p> <p>Also remember to sign up for our Founder Insight mailing list to receive exclusive startup training videos and articles every Monday and Thursday: <a >http://eepurl.com/SLa</a></p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1573226171000,
      duration: 3600000,
      id: '266317013',
      name: 'Digital Marketing Live Chat by Popular Pays VP of Product',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1579029300000,
      local_date: '2020-01-14',
      local_time: '20:15',
      updated: 1573226475000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 7,
      group: {
        created: 1539959461000,
        name: 'Product School Berlin',
        id: 30351059,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'PS-Berlin',
        who: 'Product Geeks',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/PS-Berlin/events/266317013/',
      description: '<p>***RSVP on EventBrite: <a >https://prdct.school/2PWa6DQ</a> ***</p> <p>*** DISCLAIMER: This event is ONLINE ***</p> <p>Join in and get all your Product Management questions answered during our online event with Dalyn Ward, Vice President of Product at Popular Pays.<br/>Some questions that will be answered include:<br/>1. What is the best part of being a Product Manager?<br/>2. What is the worst part of being a Product Manager?<br/>3. What do you look for in a Product Management resume and/or candidate?<br/>4. What was a difficult Product Manager interview question you’ve had? And how did you answer it?<br/>5. Have you ever felt like you didn’t understand the technology on a product? What did you do to compensate?</p> <p>Meet the Speaker: Dalyn Ward</p> <p>Dalyn Ward is a Vice President of Product at Popular Pays. He began his career as a media buyer and planner working at an agencies in NYC. Then moved into technology focused roles at digital consultancies like Huge and MCD Partners developing digital experiences for clients like Barneys, Under Armour and Discover Financial Services.</p> <p>View Speaker\'s Full Profile (<a >https://prod.school/32rskiS</a>)</p> <p>Get the FREE Product Book here (<a >https://prdct.school/2CMSqF1</a>)</p> <p>Get Your Tickets (<a >https://prdct.school/2PWa6DQ</a>)</p> <p>*Entrance not guaranteed without valid ticket from Eventbrite</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1533891843000,
      duration: 10800000,
      id: 'gdsglrybcfbqb',
      name: '69# Talk and socialize',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1584036000000,
      local_date: '2020-03-12',
      local_time: '19:00',
      updated: 1573992383000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      group: {
        created: 1372864747000,
        name: 'Elixir Berlin',
        id: 9199792,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Elixir-Berlin',
        who: 'Alchemists',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Elixir-Berlin/events/gdsglrybcfbqb/',
      description: '<p>👋 Hallo und herzlich Willkommen - we\'re back with the 69th edition of Elixir Berlin.</p> <p>⏰ Schedule</p> <p>6:45 PM: Doors open<br/>7:05 PM: Welcome &amp; Announcements<br/>7:15 PM: 🗣 TALK 1 by SPAKER ONE<br/>7:45 PM: 🍕Break 🍺<br/>8:00 PM: 🗣 TALK 2 by SPEAKER TWO<br/>8:30 PM: ⚡️ Lightning talks (Want to speak at this Meetup? Get in touch on GitHub*)<br/>8:45 PM: Socialize &amp; Chat about Elixir</p> <p>We want to encourage members of the Elixir community to share what they\'re working on. If you want to give a lightning talk at this Meetup, contact one of the organisers with a short description of your talk.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1575644545000,
      duration: 10800000,
      id: 'nkstlrybcdbjc',
      name: 'Web Frontend Co-Learning',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582741800000,
      local_date: '2020-02-26',
      local_time: '19:30',
      updated: 1575644545000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 19383642,
        name: 'co.up',
        lat: 52.50053405761719,
        lon: 13.418963432312012,
        repinned: true,
        address_1: 'Adalbertstr. 8',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1342121346000,
        name: 'OpenTechSchool Berlin',
        id: 4293362,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'opentechschool-berlin',
        who: 'Learners',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/opentechschool-berlin/events/nkstlrybcdbjc/',
      description: '<p>This is all about building things in the browser: HTML, CSS and lots of JavaScript.</p> <p>We are a friendly group that meets every Wednesday to learn together and work on our projects. Bring your laptop (otherwise we can provide one for you) and your challenges and questions. There\'s always someone around that is happy to help you or would love to get some help. No matter if you are an absolute beginner or an experienced expert, we want to learn from each other.</p> <p>Doors open latest at 19:30h (please do not ring door bell before 19:00!), introduction round at 20:00h.</p> <p>Usually there is no talks or lessons planned but we can come up with something together if there\'s interest.</p> <p>If you don\'t have a project to work on or don\'t know where to start it\'s also a good idea to do some online classes or tutorials. We\'re here to help with that, too. For example check out some of our OpenTechSchool workshop material:</p> <p>JavaScript for Beginners 1 (<a >http://opentechschool.github.io/js-beginners-1/</a>) | JavaScript for Beginners 2 (<a >http://opentechschool.github.io/js-beginners-2/</a>) | Intro to HTML/CSS (<a >http://cssclass.es/materials/</a>)</p> <p>We speak German and English, sometimes even Italian, and of course code. Just come by and check it out! Oh, and bring some snacks, maybe ;)</p> <p>You\'re also welcome to join our chat on Gitter (<a >https://gitter.im/OpenTechSchool/BLN-WFColearning</a>).</p> <p>We do have a code of conduct (<a >http://www.opentechschool.org/code-of-conduct/</a>).</p> <p>For accessibility information please check <a http://co-up.de/about.html</a> and write a message to one of us.</p> <p>****************************************************************************<br/>SAVE CO.UP</p> <p>The rent is rising and without your help our friends of co.up will be forced to close the space in January 2020. That means no more free event space for community meetups. co.up provided a home for almostt all our Berlin OpenTechSchool events for free for the last 6 years! Can you become a co.up supporting member, make a donation, or share your co.up story? We need your support – help #saveCoUp!</p> <p><a >https://co-up.de/support-us</a></p> <p>****************************************************************************</p> ',
      how_to_find_us: 'The entrance is a bit hidden in the second backyard. Look for our signs or signs of the company Clue (they are next to Co.Up). 5th floor.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1573305735000,
      duration: 7200000,
      id: '266340336',
      name: 'Customer Experience Design and Mapping | 2hr workshop | Berlin',
      rsvp_limit: 55,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1580405400000,
      local_date: '2020-01-30',
      local_time: '18:30',
      updated: 1575802782000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 39,
      group: {
        created: 1557824576000,
        name: 'Customer Centric Strategy - Workshops - Berlin',
        id: 31901063,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Customer-Centric-Strategy-Workshops-Berlin',
        who: 'Members',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Customer-Centric-Strategy-Workshops-Berlin/events/266340336/',
      description: '<p>Learn by doing</p> <p>This event is going to be an interactive workshop. We\'re going to help a non-profit organization with its challenges. We present you a challenge, we\'ll work together to solve it.</p> <p>During this workshop, you practice<br/>✔ How to collect and organize feedback from customer interviews<br/>✔ How to use these insights to form user personas<br/>✔ How to create the customer journey map for any of the user personas<br/>✔ How to identify the pain points in each customer journey map<br/>✔ How to flip the pain points into opportunities using HMW questions<br/>✔ How to prioritize opportunities using Product Growth-User Needs and Effort-Impact sheets</p> <p>About Organizers</p> <p>Behrad Mirafshar<br/><a >https://www.linkedin.com/in/behradmirafshar/</a><br/>Behrad has experience in managing and designing products of various sizes. He was part of two founding teams and raised over +10M in venture capital and consulted companies across different industries such as Siemens, Volvo, and Wefox.</p> <p>Nicolaj Grabert<br/><a >https://www.linkedin.com/in/nicolaj-grabert-477821128/</a><br/>\'What is the photosynthesis we have to come up with today, for a future without melting ice, rising sea levels and bad forecasts of the future?\' 🔮</p> <p>Schedule</p> <p>19:00 - Welcome<br/>19:15 - Into Personas and Customer journey mapping<br/>19:30 - Introduction to the challenge<br/>19:45 - Define the user persona<br/>20:20 - Design the customer journey map<br/>21:05 - Present your findings<br/>21:30 - Wrap up</p> <p>About our expertise...</p> <p>At Bonanza Design, we\'d like to call ourselves an innovation powerhouse where we work on the toughest challenges. We help<br/>✔ Companies to innovate at a faster pace<br/>✔ Organizations to move towards more sustainable future<br/>✔ Companies to accelerate through the phase of digital transformation<br/>✔ Startup to define their customer experience strategies &amp; design applications that matter</p> <p>Instagram: <a >https://www.instagram.com/bonanzadesign/</a></p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1545395196000,
      duration: 7200000,
      id: 'kpcqnqyzqbgc',
      name: 'APX Pitch Tuesdays',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1577203200000,
      local_date: '2019-12-24',
      local_time: '17:00',
      rsvp_close_offset: 'PT24H',
      updated: 1545395196000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 25900732,
        name: 'APX Axel Springer Porsche GmbH & Co. KG',
        lat: 52.505592346191406,
        lon: 13.394889831542969,
        repinned: true,
        address_1: 'Markgrafenstraße 12-14',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1542565400000,
        name: 'APX Axel Springer and Porsche - Berlin',
        id: 30551789,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'APX-Axel-Springer-and-Porsche-Berlin',
        who: 'Members',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/APX-Axel-Springer-and-Porsche-Berlin/events/kpcqnqyzqbgc/',
      description: '<p>Pitch Tuesdays is our weekly startup showcase, where APX portfolio founders will pitch for their ideas and the companies’ current status. This is an opportunity for them to excel in their public speaking skills and receive feedback from a public audience as part of the 100 days investor ready program.</p> <p>We often have visits from Master’s students, partners, investors, and employees from our shareholders: Axel Springer and Porsche. The best part? You can take part in it! This is valuable training for the APX portfolio founders, opportunities for our portfolio companies to gather insightful feedback, and also a great networking opportunity for you!</p> <p>Swing by our offices for a drink, see the pitches, and vote for your favourite.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1574279906000,
      duration: 10800000,
      id: 'nkstlrybccbtb',
      name: 'Web Frontend Co-Learning',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1579113000000,
      local_date: '2020-01-15',
      local_time: '19:30',
      updated: 1575644546000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 7,
      venue: {
        id: 19383642,
        name: 'co.up',
        lat: 52.50053405761719,
        lon: 13.418963432312012,
        repinned: true,
        address_1: 'Adalbertstr. 8',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1342121346000,
        name: 'OpenTechSchool Berlin',
        id: 4293362,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'opentechschool-berlin',
        who: 'Learners',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/opentechschool-berlin/events/nkstlrybccbtb/',
      description: '<p>This is all about building things in the browser: HTML, CSS and lots of JavaScript.</p> <p>We are a friendly group that meets every Wednesday to learn together and work on our projects. Bring your laptop (otherwise we can provide one for you) and your challenges and questions. There\'s always someone around that is happy to help you or would love to get some help. No matter if you are an absolute beginner or an experienced expert, we want to learn from each other.</p> <p>Doors open latest at 19:30h (please do not ring door bell before 19:00!), introduction round at 20:00h.</p> <p>Usually there is no talks or lessons planned but we can come up with something together if there\'s interest.</p> <p>If you don\'t have a project to work on or don\'t know where to start it\'s also a good idea to do some online classes or tutorials. We\'re here to help with that, too. For example check out some of our OpenTechSchool workshop material:</p> <p>JavaScript for Beginners 1 (<a >http://opentechschool.github.io/js-beginners-1/</a>) | JavaScript for Beginners 2 (<a >http://opentechschool.github.io/js-beginners-2/</a>) | Intro to HTML/CSS (<a >http://cssclass.es/materials/</a>)</p> <p>We speak German and English, sometimes even Italian, and of course code. Just come by and check it out! Oh, and bring some snacks, maybe ;)</p> <p>You\'re also welcome to join our chat on Gitter (<a >https://gitter.im/OpenTechSchool/BLN-WFColearning</a>).</p> <p>We do have a code of conduct (<a >http://www.opentechschool.org/code-of-conduct/</a>).</p> <p>For accessibility information please check <a http://co-up.de/about.html</a> and write a message to one of us.</p> <p>****************************************************************************<br/>SAVE CO.UP</p> <p>The rent is rising and without your help our friends of co.up will be forced to close the space in January 2020. That means no more free event space for community meetups. co.up provided a home for almostt all our Berlin OpenTechSchool events for free for the last 6 years! Can you become a co.up supporting member, make a donation, or share your co.up story? We need your support – help #saveCoUp!</p> <p><a >https://co-up.de/support-us</a></p> <p>****************************************************************************</p> ',
      how_to_find_us: 'The entrance is a bit hidden in the second backyard. Look for our signs or signs of the company Clue (they are next to Co.Up). 5th floor.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1570449837000,
      duration: 7200000,
      id: '265473158',
      name: 'DYDC #4 – Open Mentoring',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1576602000000,
      local_date: '2019-12-17',
      local_time: '18:00',
      updated: 1576099821000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 7,
      group: {
        created: 1559477163000,
        name: 'Design Your Design Career',
        id: 32085052,
        join_mode: 'approval',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Design-Your-Design-Career',
        who: 'Mitglieder',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Design-Your-Design-Career/events/265473158/',
      description: '<p>For our Xmas session I will host an open group mentoring at betahaus. You can bring whatever topic you would like to address in an extended mastermind setting. Our modus will be similar to group critique at design school: you will receive inquiries, feedback, and advice from everybody else in the group. I, Sascha, will facilitate, supervise, and provide suitable prompts for mentoring. You will thus not only get constructive feedback for your own challenges but also get some insights how to coach and mentor others, thus building important leadership skills for any kind of career track.</p> <p>True to the season there will be some mulled wine on the table. Bring some cookies or other festive snacks to keep us from getting drunk right away ;)</p> <p>Agenda</p> <p>18:00 Door open<br/>18:15 Intros<br/>18:20 Open group mentoring<br/>20:00 Wrap-up and reflection</p> <p>ATTENTION: Seats are strictly limited this time. Please cancel at least 4h in advance in case you cannot make it</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1574883041000,
      duration: 10800000,
      id: '266787443',
      name: 'Berlin Developer Meeting - February 2020 - team neusta GmbH',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582738200000,
      local_date: '2020-02-26',
      local_time: '18:30',
      updated: 1574956203000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 26752913,
        name: 'team neusta GmbH',
        lat: 52.503173828125,
        lon: 13.390714645385742,
        repinned: false,
        address_1: 'Friedrichstrasse 230 (Enter Hedemannstrasse 14)',
        city: 'Berlin',
        country: 'DE',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1345066391000,
        name: 'Berlin Salesforce Developer Group',
        id: 4557902,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Berlin-Salesforce-Platform-Developer-User-Group',
        who: 'Developers',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Berlin-Salesforce-Platform-Developer-User-Group/events/266787443/',
      description: '<p>THIS IS A FREE MEETING - PLEASE FINISH YOUR RSVP IN THE LINK BELOW</p> <p>&lt;br/&gt;<a >https://trailblazercommunitygroups.com/events/details/salesforce-berlin-de-developers-group-presents-berlin-developer-meeting-february-2020-team-neusta-gmbh/</a></p> <p>&amp;lt;p&amp;gt;Book your calendars for our first Salesforce Developer Meeting of 2020. More details coming soon and please let us know if you would like to present. &amp;lt;/p&amp;gt;&lt;/p&gt;</p> <p>Agenda&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>&lt;br/&gt;---&lt;br/&gt;</p> <p>&lt;br/&gt;<br/>Hosted By&lt;br/&gt;</p> <p>Ankit Taneja, Leader&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>Alexis Kasperavičius, Leader&lt;br/&gt;</p> <p>Hi There! I grew up in Los Angeles and have been spending most of my time in Berlin, Germany since 2013.</p> <p>I have been developing on the Salesforce platform since 2006, and was previously a video game producer (3DO, Playstation) &amp;amp;amp; film post-production supervisor.</p> <p>When not developing on Salesforce I like cooking, playing the horn in various orchestras and chamber groups around Berlin, and exploring old technology like telephones, telegraphs and locomotives throughout Germany. Oh, and learning German...&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>&lt;br/&gt;---&lt;br/&gt;</p> <p>&lt;br/&gt;<br/>Global Partner&lt;br/&gt;</p> <p>Trailblazer Community (<a >http://trailblazer.salesforce.com)&lt;br/&gt</a>;<br/>Join the Trailblazer Community on the fun path to success with Salesforce. We welcome all, and we love to succeed together. Connect with fellow Trailblazers by collaborating online, joining Community Groups, and learning from amazing Community Leaders. Then, step up to inspire the next generation.&lt;br/&gt;<br/>&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>&lt;br/&gt;<br/>Partner&lt;br/&gt;</p> <p>team neusta GmbH (<a >https://www.team-neusta.de/)&lt;br/&gt</a>;<br/>team neusta is much more than a software developer: our digital family is an owner-managed group of companies specializing in the development and connection of analogue and digital communication platforms.&lt;br/&gt;<br/>&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>&lt;br/&gt;---&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>THIS IS A FREE MEETING - PLEASE FINISH YOUR RSVP IN THE LINK BELOW</p> <p>&lt;br/&gt;<a >https://trailblazercommunitygroups.com/events/details/salesforce-berlin-de-developers-group-presents-berlin-developer-meeting-february-2020-team-neusta-gmbh/</a></p> ',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1575644545000,
      duration: 10800000,
      id: 'nkstlrybccblb',
      name: 'Web Frontend Co-Learning',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1578508200000,
      local_date: '2020-01-08',
      local_time: '19:30',
      updated: 1575644545000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      venue: {
        id: 19383642,
        name: 'co.up',
        lat: 52.50053405761719,
        lon: 13.418963432312012,
        repinned: true,
        address_1: 'Adalbertstr. 8',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1342121346000,
        name: 'OpenTechSchool Berlin',
        id: 4293362,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'opentechschool-berlin',
        who: 'Learners',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/opentechschool-berlin/events/nkstlrybccblb/',
      description: '<p>This is all about building things in the browser: HTML, CSS and lots of JavaScript.</p> <p>We are a friendly group that meets every Wednesday to learn together and work on our projects. Bring your laptop (otherwise we can provide one for you) and your challenges and questions. There\'s always someone around that is happy to help you or would love to get some help. No matter if you are an absolute beginner or an experienced expert, we want to learn from each other.</p> <p>Doors open latest at 19:30h (please do not ring door bell before 19:00!), introduction round at 20:00h.</p> <p>Usually there is no talks or lessons planned but we can come up with something together if there\'s interest.</p> <p>If you don\'t have a project to work on or don\'t know where to start it\'s also a good idea to do some online classes or tutorials. We\'re here to help with that, too. For example check out some of our OpenTechSchool workshop material:</p> <p>JavaScript for Beginners 1 (<a >http://opentechschool.github.io/js-beginners-1/</a>) | JavaScript for Beginners 2 (<a >http://opentechschool.github.io/js-beginners-2/</a>) | Intro to HTML/CSS (<a >http://cssclass.es/materials/</a>)</p> <p>We speak German and English, sometimes even Italian, and of course code. Just come by and check it out! Oh, and bring some snacks, maybe ;)</p> <p>You\'re also welcome to join our chat on Gitter (<a >https://gitter.im/OpenTechSchool/BLN-WFColearning</a>).</p> <p>We do have a code of conduct (<a >http://www.opentechschool.org/code-of-conduct/</a>).</p> <p>For accessibility information please check <a >http://co-up.de/about.html</a> and write a message to one of us.</p> <p>****************************************************************************<br/>SAVE CO.UP</p> <p>The rent is rising and without your help our friends of co.up will be forced to close the space in January 2020. That means no more free event space for community meetups. co.up provided a home for almostt all our Berlin OpenTechSchool events for free for the last 6 years! Can you become a co.up supporting member, make a donation, or share your co.up story? We need your support – help #saveCoUp!</p> <p><a https://co-up.de/support-us</a></p> <p>****************************************************************************</p> ',
      how_to_find_us: 'The entrance is a bit hidden in the second backyard. Look for our signs or signs of the company Clue (they are next to Co.Up). 5th floor.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1573799327000,
      duration: 7200000,
      id: '266485754',
      name: '(paid) online AI course: Deep Learning for developers',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1578420000000,
      local_date: '2020-01-07',
      local_time: '19:00',
      updated: 1573799327000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 10,
      group: {
        created: 1536528433000,
        name: 'Berlin AI Developers Group',
        id: 29753920,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Berlin-AI-Tech-Talk',
        who: 'AI Engineer',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Berlin-AI-Tech-Talk/events/266485754/',
      description: '<p>We are starting the new session for the popular 4-week AI course: Deep Learning for Developers.<br/>This course is online live course. You can listen, watch, interact, Q&amp;A with instructors from anywhere around the world. Miss the live session due to time zone or conflict? learn session replay at any time afterwards.</p> <p>Start date: Jan. 7, 10am PT (US pacific time, check your local time zone).<br/>* 8 sessions, 16 hours<br/>* 10 live lectures, 16 hands-on code labs.<br/>* Live Sessions, Real time interaction<br/>* Forum supports to projects and homeworks</p> <p>Enrollment:<br/><a >https://learn.xnextcon.com/course/coursedetails/C20010710</a></p> <p>Details:<br/>learn deep learning by building deep learning models and projects.<br/>The course takes unique project focused approach to teach you deep learning by building deep learning models. The instructor will walk you through a series of curated projects, and explain the key concepts as they arise. Students will learn the theory and how these models work under the hood while writing code, and building neural networks.</p> <p>The course balances learning theory, working on projects, and also hearing from guest speakers who are industry practitioners in the field.</p> <p>Students who take this course will be able to:<br/>* Identify and frame problems that can be solved by deep learning<br/>* Choose the right techniques to the problems<br/>* Understand key deep learning concepts and how deep learning models work<br/>* Identify and fix problems with messy datasets<br/>* Build deep neural nets for classification and regression using the Keras framework<br/>* Build convolutional neural networks for image classification, object localization and segmentation using the Keras<br/>* Discuss the parts and processes involved in building large scale deep learning applications</p> <p>Online AI tech talks, courses, bootcamps : <a >https://learn.xnextcon.com</a></p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1546515973000,
      duration: 7200000,
      id: '257740935',
      name: 'Kick Off',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1580410800000,
      local_date: '2020-01-30',
      local_time: '20:00',
      updated: 1575030875000,
      utc_offset: 3600000,
      waitlist_count: 2,
      yes_rsvp_count: 40,
      group: {
        created: 1546515256000,
        name: 'Fediverse Berlin',
        id: 30829662,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Fediverse-Berlin',
        who: 'Members',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Fediverse-Berlin/events/257740935/',
      description: '<p>- How was the Fediverse born, and what are the technologies that underpin it?<br/>- Helicopter view of Fediverse architecture<br/>- Hands-on deep dive into the Fediverse<br/>- Want to build an activitypub powered social network? Here\'s how...</p> <p>We are looking forward to a fun evening!</p> <p>We will provide drinks and snacks :)</p> <p>And we are going to announce the location in a couple of days</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1562337136000,
      duration: 10800000,
      id: 'msgmdrybcfbnb',
      name: 'Vue.js // Berlin',
      rsvp_limit: 75,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1583863200000,
      local_date: '2020-03-10',
      local_time: '19:00',
      updated: 1562337136000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      venue: {
        id: 25963672,
        name: 'fromAtoB',
        lat: 52.523590087890625,
        lon: 13.40488338470459,
        repinned: true,
        address_1: 'Dircksenstrasse 47',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1485860967000,
        name: 'Vue.js // Berlin',
        id: 22176763,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Vue-js-Berlin',
        who: 'Vue\'sers',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Vue-js-Berlin/events/msgmdrybcfbnb/',
      description: '<p>Lets talk about Vue.js the Vue.js ecosystem!</p> <p>**** Presentation ****</p> <p>TBA</p> <p>We will have Coffee, Mate, Beer …and probably Pizza!</p> <p>**** Code of Conduct ****<br/>We follow the Berlin Code Of Conduct and expect every attendee to do the same. More details can be found on <a >http://berlincodeofconduct.org</a> .</p> ',
      how_to_find_us: 'second backyard, aufgang e (important!), 3rd level.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1571162267000,
      duration: 7200000,
      id: 'qptdkrybccbcc',
      name: 'Django User Group Berlin',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1579631400000,
      local_date: '2020-01-21',
      local_time: '19:30',
      updated: 1571162267000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      group: {
        created: 1369857361000,
        name: 'Django User Group Berlin (djub)',
        id: 8697102,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'django-user-group-berlin',
        who: 'Members',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/django-user-group-berlin/events/qptdkrybccbcc/',
      description: '<p>Lets meet and talk about Django.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1574091995000,
      duration: 7200000,
      id: '266557250',
      name: 'Le Wagon Talk with Narbeh Mirzaei, HelloFresh 🌱',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1580319000000,
      local_date: '2020-01-29',
      local_time: '18:30',
      updated: 1574092790000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 9,
      venue: {
        id: 26086918,
        name: 'Le Wagon Berlin Coding Bootcamp',
        lat: 52.50699996948242,
        lon: 13.39120101928711,
        repinned: true,
        address_1: 'Rudi-Dutschke-Straße 26',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1480930828000,
        name: 'Le Wagon Berlin - Coding Bootcamp',
        id: 21449749,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Le-Wagon-Berlin-Coding-Bootcamp',
        who: 'Members',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Le-Wagon-Berlin-Coding-Bootcamp/events/266557250/',
      description: '<p>⭐️⭐️⭐️ REGISTER VIA EVENTBRITE: <a >https://lew.ag/HFTalkJan</a> ⭐️⭐️⭐️</p> <p>Narbeh will be sharing insights with us about what it takes to kick-start your career as a software engineer! He will discuss how to land your first job and grow your career as a developer 👩\u200d💻 He will also tell us about his tech team at HelloFresh and the challenges of building successful engineering organizations.</p> <p>⚡️Narbeh Mirzaei ⚡️<br/>Narbeh Mirzaei is a software engineer, entrepreneur and technologist based in Berlin. He has over a decade of experience in consumer startups, specifically in hospitality, e-commerce and travel industries. He is currently leading the Payments Tech team at HelloFresh.</p> <p>🌱About HelloFresh 🌱<br/>HelloFresh SE is the leading global meal-kit company and operates in the U.S., the United Kingdom, Germany, the Netherlands, Belgium, Luxembourg, Australia, Austria, Switzerland, Canada, New Zealand and Sweden. HelloFresh delivered 69 million meals to 2.6 million active customers worldwide in Q3 2019 (July 1 - September 30, 2019).</p> <p>HelloFresh was founded in Berlin in November 2011 and went public on the Frankfurt Stock Exchange in November 2017. HelloFresh has offices in New York, Berlin, London, Amsterdam, Zurich, Sydney, Toronto, Auckland and Copenhagen.</p> <p>⭐️⭐️⭐️ REGISTER VIA EVENTBRITE: <a lkJan</a> ⭐️⭐️⭐️</p> <p>***************************************</p> <p>🚀About Le Wagon 🚀<br/>Le Wagon is Europe\'s leading coding school for entrepreneurs and creative people. We are now present in 30 cities worldwide, with over 120 startups in operation, and have been rated the no#1 coding bootcamp worldwide on Course Report &amp; Switchup! Our 9-week, full-stack web development course equips aspiring entrepreneurs, product managers, designers, and junior developers with the technical skills they need to build great products and startups!</p> <p>***************************************</p> <p>Join our Meetup group: <a >https://www.meetup.com/Le-Wagon-Berlin-Coding-Bootcamp/events/246861962/</a></p> <p>Like us on Facebook: <a >http://facebook.com/lewagonberlin</a></p> <p>Follow us on Twitter: twitter.com/lewagonberlin</p> <p>Look at some lovely photos on Instagram: <a >https://www.instagram.com/lewagonberlin/</a></p> <p>***************************************</p> <p>We look forward to meeting you soon!</p> <p>Team Le Wagon</p> ',
      how_to_find_us: 'Inside the courtyard, on the right, 5th floor, ',
      visibility: 'public',
      pro_is_email_shared: true,
      member_pay_fee: false
    },
    {
      created: 1573227270000,
      duration: 3600000,
      id: '266317500',
      name: 'Webinar: What are the Tools and Frameworks for a PM by Babbel PM',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1579116600000,
      local_date: '2020-01-15',
      local_time: '20:30',
      updated: 1574180583000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 44,
      group: {
        created: 1539959461000,
        name: 'Product School Berlin',
        id: 30351059,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'PS-Berlin',
        who: 'Product Geeks',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/PS-Berlin/events/266317500/',
      description: '<p>***RSVP on EventBrite: <a >https://prdct.school/2WZs35J</a> ***</p> <p>*** DISCLAIMER: This event is ONLINE ***</p> <p>Product Management today is the hot trend that everyone wants to be a part of. And there\'s lots that you can learn from established professionals. So when you\'re starting out your Product Management career, how should you go about it? What are the key tools you need to consider?<br/>Come find out this Thursday with Partha Dash from Babbel.</p> <p>Main takeaways:<br/>- How to distinguish between Problem Space and Solution Space<br/>- How to design a solution with a data-driven approach<br/>- Tools and techniques for a lean product development process</p> <p>Meet the Speaker: Partha Dash</p> <p>Partha Dash is a Product Manager at Babbel in Berlin. He has previously worked as Product Owner at fundsUP. Partha became a Product Manager and found that his wide range of skills was a perfect match for a career in product.</p> <p>View the Speaker\'s LinkedIn (<a >https://www.linkedin.com/in/parthadash/</a>)</p> <p>Get the FREE Product Book here (<a >https://prdct.school/2CMSqF1</a>)</p> <p>Product School (<a >https://www.productschool.com/?utm_source=eventbrite&amp;utm_medium=events&amp;utm_campaign=EventsPage</a>) is the global leader in product management training, with over 10,000 alumni, 20 campuses worldwide and a live online campus. Product School’s certificates (PMC™,FPMC™,PLC™) are the most important industry-recognized certificates for product managers; all of our instructors are senior-level product managers working at top technology companies such as Google, Facebook, Airbnb, PayPal, LinkedIn, and Netflix.</p> <p>Get Your Tickets (<a >https://prdct.school/2WZs35J</a>)</p> <p>*Entrance not guaranteed without valid ticket from Eventbrite</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1541410810000,
      duration: 7200000,
      id: 'jmwllqybcdbgb',
      name: 'Silicon Allee Monthly Meetup',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1580803200000,
      local_date: '2020-02-04',
      local_time: '09:00',
      updated: 1541410810000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      venue: {
        id: 25726180,
        name: 'R/D Coffee Bar',
        lat: 52.53022766113281,
        lon: 13.384085655212402,
        repinned: true,
        address_1: 'Chausseestraße 19',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1511954195000,
        name: 'Silicon Allee Events',
        id: 26735498,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Silicon-Allee-Events',
        who: 'Members',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Silicon-Allee-Events/events/jmwllqybcdbgb/',
      description: '<p>Join the team at the renowned Silicon Allee meet up for the latest tech talk in Berlin whilst networking and enjoying great coffee. We\'ve hosted the monthly meetup for over 6 years and always attract a wide range of Berlin\'s tech community.</p> <p>It\'s open for everyone working in, or curious about tech startups, whether you are established in Berlin or a new arrival in town. Guests are encouraged to share their stories and discover what\'s happening in Europe\'s leading tech city!</p> <p>Connect with us before the meet up :</p> <p><a >http://www.siliconallee.com/</a></p> <p>#BerlinStartups #Since2011</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1564396870000,
      duration: 27900000,
      id: '263549270',
      name: '👩\u200d💻Women\'s Coding Workshop - Learn to code for free! JANUARY EDITION',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1578734100000,
      local_date: '2020-01-11',
      local_time: '10:15',
      updated: 1574087620000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 25398147,
        name: 'Le Wagon Berlin',
        lat: 52.50701141357422,
        lon: 13.391451835632324,
        repinned: true,
        address_1: 'Rudi-Dutschke-Str. 26, 10969 Berlin',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1480930828000,
        name: 'Le Wagon Berlin - Coding Bootcamp',
        id: 21449749,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Le-Wagon-Berlin-Coding-Bootcamp',
        who: 'Members',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Le-Wagon-Berlin-Coding-Bootcamp/events/263549270/',
      description: '<p>⭐️⭐️⭐️PLEASE APPLY HERE: <a >https://lew.ag/JanMarWCDapply</a> ⭐️⭐️⭐️</p> <p>This is a FREE full day workshop on the basics of coding &amp; creating your first landing page from scratch with HTML and CSS!</p> <p>⚡️Get a taste of web development and find out if it is for you<br/>⚡️Meet other women interested in learning to code<br/>⚡️Receive a 500€ scholarship for the #1 coding bootcamp<br/>⚡️Build your own landing page with our brilliant female teaching assistants</p> <p>👉SOUNDS GOOD? APPLY NOW! <a >https://lew.ag/JanMarWCDapply</a></p> <p>Registration closes on the 1st of January. The results of the selection process will be announced shortly after 📣</p> <p>***************************************</p> <p>We are well aware that women as a demographic are still very much underrepresented in the tech industry. Unfortunately even today women hold less than 25% of the jobs in the field.</p> <p>Le Wagon believes that a more diverse environment is a more creative and effective one. We want to empower women by giving them the knowledge and skills needed to thrive in tech 👩\u200d💻 That’s why we’re more than happy to offer partial scholarships for every woman who will attend our coding events 🤩</p> <p>You can learn more about our gender diversity agenda here: <a >https://lew.ag/2RzuM6z</a> 👀</p> <p>***************************************</p> <p>About Le Wagon 🚀</p> <p>Le Wagon is Europe\'s leading coding school for entrepreneurs and creative people. We are now present in 30 major cities worldwide, and have been rated the #1 coding bootcamp worldwide on Course Report &amp; Switchup! Our 9-week, full-stack web development course equips aspiring entrepreneurs, product managers, designers, and junior developers with the technical skills they need to build great products and startups.</p> <p>Next batches in Berlin are January 13th - March 13th 2020. Further details about the course and how to apply can be found here (<a >https://www.lewagon.com/berlin</a>).</p> <p>***************************************</p> <p>We look forward to meeting you soon!</p> <p>Team Le Wagon 🌟</p> ',
      how_to_find_us: 'Inside the courtyard, 5th floor on the right',
      visibility: 'public',
      pro_is_email_shared: true,
      member_pay_fee: false
    },
    {
      local_time: '20:00',
      local_date: '2019-12-31',
      link: 'https://www.meetup.com/fr-FR/Fine-Dining-in-Berlin/events/266160633/',
      visibility: 'public_limited',
      group: {
        created: 1429756509000,
        name: 'Fine Dining in Berlin',
        id: 18559794,
        join_mode: 'approval',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Fine-Dining-in-Berlin',
        who: 'Fine Diners',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      waitlist_count: 16,
      yes_rsvp_count: 21,
      duration: 25200000,
      time: 1577818800000,
      utc_offset: 3600000,
      name: 'NEW YEAR\'S EVE PRIVATE PARTY!!! (Tentative - to be confirmed mid December)',
      id: '266160633'
    },
    {
      created: 1562337136000,
      duration: 10800000,
      id: 'msgmdrybccbsb',
      name: 'Vue.js // Berlin',
      rsvp_limit: 75,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1579024800000,
      local_date: '2020-01-14',
      local_time: '19:00',
      updated: 1562337136000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 39,
      venue: {
        id: 25963672,
        name: 'fromAtoB',
        lat: 52.523590087890625,
        lon: 13.40488338470459,
        repinned: true,
        address_1: 'Dircksenstrasse 47',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1485860967000,
        name: 'Vue.js // Berlin',
        id: 22176763,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Vue-js-Berlin',
        who: 'Vue\'sers',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Vue-js-Berlin/events/msgmdrybccbsb/',
      description: '<p>Lets talk about Vue.js the Vue.js ecosystem!</p> <p>**** Presentation ****</p> <p>TBA</p> <p>We will have Coffee, Mate, Beer …and probably Pizza!</p> <p>**** Code of Conduct ****<br/>We follow the Berlin Code Of Conduct and expect every attendee to do the same. More details can be found on <a >http://berlincodeofconduct.org</a> .</p> ',
      how_to_find_us: 'second backyard, aufgang e (important!), 3rd level.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1533891843000,
      duration: 10800000,
      id: 'gdsglrybcdbrb',
      name: '68# Talk and socialize',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1581616800000,
      local_date: '2020-02-13',
      local_time: '19:00',
      updated: 1573992342000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      group: {
        created: 1372864747000,
        name: 'Elixir Berlin',
        id: 9199792,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Elixir-Berlin',
        who: 'Alchemists',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Elixir-Berlin/events/gdsglrybcdbrb/',
      description: '<p>👋 Hallo und herzlich Willkommen - we\'re back with the 68th edition of Elixir Berlin.</p> <p>⏰ Schedule</p> <p>6:45 PM: Doors open<br/>7:05 PM: Welcome &amp; Announcements<br/>7:15 PM: 🗣 TALK 1 by SPAKER ONE<br/>7:45 PM: 🍕Break 🍺<br/>8:00 PM: 🗣 TALK 2 by SPEAKER TWO<br/>8:30 PM: ⚡️ Lightning talks (Want to speak at this Meetup? Get in touch on GitHub*)<br/>8:45 PM: Socialize &amp; Chat about Elixir</p> <p>We want to encourage members of the Elixir community to share what they\'re working on. If you want to give a lightning talk at this Meetup, contact one of the organisers with a short description of your talk.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1575916800000,
      duration: 439200000,
      id: 'tckwlrybccbmb',
      name: 'Web Audio Stammtisch',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1578592800000,
      local_date: '2020-01-09',
      local_time: '19:00',
      updated: 1575916800000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      group: {
        created: 1427211557000,
        name: 'Berlin Web Audio Meetup',
        id: 18518242,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Berlin-Web-Audio-Meetup',
        who: 'music makers',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Berlin-Web-Audio-Meetup/events/tckwlrybccbmb/',
      description: '<p>🔊 After the amazing Web Audio conference in Trondheim we collectively decided that it\'d be great to have an informal gathering every month - no structured talks, just a loose hangout to keep in touch and exchange ideas...</p> <p>🌐 The exact location is to be determined, but save the date for the first one! (if you have a suggestion, feel free to put them in the comments)</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1562337136000,
      duration: 10800000,
      id: 'msgmdrybcdbpb',
      name: 'Vue.js // Berlin',
      rsvp_limit: 75,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1581444000000,
      local_date: '2020-02-11',
      local_time: '19:00',
      updated: 1562337136000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 8,
      venue: {
        id: 25963672,
        name: 'fromAtoB',
        lat: 52.523590087890625,
        lon: 13.40488338470459,
        repinned: true,
        address_1: 'Dircksenstrasse 47',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1485860967000,
        name: 'Vue.js // Berlin',
        id: 22176763,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Vue-js-Berlin',
        who: 'Vue\'sers',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Vue-js-Berlin/events/msgmdrybcdbpb/',
      description: '<p>Lets talk about Vue.js the Vue.js ecosystem!</p> <p>**** Presentation ****</p> <p>TBA</p> <p>We will have Coffee, Mate, Beer …and probably Pizza!</p> <p>**** Code of Conduct ****<br/>We follow the Berlin Code Of Conduct and expect every attendee to do the same. More details can be found on <a >http://berlincodeofconduct.org</a> .</p> ',
      how_to_find_us: 'second backyard, aufgang e (important!), 3rd level.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1572602954000,
      duration: 7200000,
      id: 'gnxskryzqbwb',
      name: 'Terrible Football Berlin',
      rsvp_limit: 42,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1576602000000,
      local_date: '2019-12-17',
      local_time: '18:00',
      updated: 1572602954000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      venue: {
        id: 25927437,
        name: 'SportPark Poststadion Moabit',
        lat: 52.53022384643555,
        lon: 13.359557151794434,
        repinned: true,
        address_1: 'SportPark Poststadion Moabit, Lehrter Str. 59, 10557 Berlin',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1537356262000,
        name: 'Terrible Football Berlin',
        id: 29870797,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Terrible-Football-Berlin',
        who: 'Terrible Footballers',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Terrible-Football-Berlin/events/gnxskryzqbwb/',
      description: '<p>Welcome to Terrible Football Berlin!</p> <p>Do you want to play football but don\'t want to pay? Are you a bit unfit, a bit old, or a bit Terrible? Want to have a relaxed kick about, and a couple of beers after? Then Terrible Football is for you!</p> <p>Anyone can play: any ability, any age and any gender. Terrible Football is about miss kicked clearances, sweet half volleys and desperate diving saves. We play in the rain, sun or snow. It\'s completely free, and always will be. It\'s open, inclusive and Terrible.</p> <p>You just need to RSVP and turn up on the day.</p> <p>We usually play on astro (artificial grass) and sometimes on grass, depending on numbers. Bibs, balls and cones are taken care of! Just bring sporty clothes and a pair of cleats and you\'ll be good to go!</p> <p>Trouble finding us? Send a message in our Telegram group <a >https://t.me/joinchat/OkWQBBcw3b7ptauwrIEfig</a> and we\'ll help you out. You\'ll also stay up to date with last minute changes!</p> <p>See you on the pitch!</p> <p>... and stay Terrible!</p> ',
      how_to_find_us: 'Meeting point is at the bouldering hall. If you have troubles finding the location, send us a message on the Telegram group https://t.me/joinchat/OkWQBBcw3b7ptauwrIEfig.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1574328994000,
      duration: 7200000,
      id: '266632204',
      name: 'Von der Idee zur eigenen Firma in nur 5 Tagen (Einführung)',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1576519200000,
      local_date: '2019-12-16',
      local_time: '19:00',
      updated: 1574809611000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 56,
      venue: {
        id: 26750890,
        name: 'Rent24',
        lat: 52.513755798339844,
        lon: 13.396493911743164,
        repinned: false,
        address_1: 'Oberwallstraße 6',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1569435730000,
        name: 'Von der Idee zur eigenen Firma in nur 5 Tagen [Berlin]',
        id: 32811294,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Von-der-Idee-zu-eigenen-Firma-in-nur-5-Tagen',
        who: 'Members',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Von-der-Idee-zu-eigenen-Firma-in-nur-5-Tagen/events/266632204/',
      description: '<p>Viele Menschen sind überwältigt von all den Aufgaben und Formalitäten, die mit der Gründung eines eigenen Unternehmens verbunden sind. Ein Startup kann jedoch bereits nach einer Woche gestartet werden. Wir betrachten sowohl die Geschäftsentwicklung als auch die persönliche Entwicklung, denn ein Unternehmen kann nur so groß werden wie du als Person.</p> <p>Dies ist eine Einführung in die Konzepte, wie man in 5 Tagen von der Idee zum Unternehmen kommt:</p> <p>- Warum dauert es normalerweise so lange, ein Unternehmen zu gründen und wie kann man es überwinden?<br/>- Welche Persönlichkeitsmerkmale werden als Unternehmer benötigt?<br/>- Typische Fallstricke und Wege zur Gründung deines Unternehmens<br/>- Notwendige Schritte zur Gründung deines Unternehmens In Deutschland</p> <p>Wir fangen mit einer Präsentation von ca. 70 Minuten an. Danach gibt es eine offene Fragerunde und Gedankenaustausch.</p> <p>Diese Veranstaltung steht potenziellen Gründern aus allen Geschäftsbereichen offen, egal ob Sie bereits eine konkrete Idee haben oder noch auf der Suche sind.</p> <p>Die Veranstaltung ist auf Deutsch.</p> <p>Bitte über Eventbrite für das Event anmelden: <a >https://www.eventbrite.de/e/von-der-idee-zur-firma-in-nur-5-tagen-einfuhrung-berlin-registration-79115557763</a></p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1575387238000,
      duration: 10800000,
      id: '266919296',
      name: 'Meetup #1: Software Verification for Developers',
      rsvp_limit: 40,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1579109400000,
      local_date: '2020-01-15',
      local_time: '18:30',
      updated: 1575391758000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 23,
      group: {
        created: 1574589216000,
        name: 'Berlin Software Verification Meetup',
        id: 33042965,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Berlin-Software-Verification-Meetup',
        who: 'Members',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Berlin-Software-Verification-Meetup/events/266919296/',
      description: '<p>I am happy to announce the first meetup and the first speaker.</p> <p>Dr. Yegor Derevenets – Software Verification for Developers</p> <p>The abstract:</p> <p><br/>Sometimes, when you build software, you want to be sure that you have built it right. Examples include software for safety-critical systems, code that works with data from untrusted sources (e.g., protocol parsers), parallel algorithms, which are usually impossible to get right the first time, and many more. Software verification gives you a helping hand in such cases.</p> <p>In this talk I will give an overview of the software verification methods and highlight those that can be used without diving deeply into the theory. The survey will cover methods for ensuring correctness: theorem proving, model checking, — as well as methods for bug hunting: from good old testing to automatic test generation using concolic testing and fuzzing, and making compiler write checks for you.<br/></p> <p>Yegor is a Software Engineer at Yandex.Technology GmbH.</p> <p>---</p> <p>Agenda:</p> <p>18:30: Open doors<br/>19:00: Intro<br/>19:10: Presentation<br/>20:10-21:30: Networking and drinks</p> <p>**We have not found a host for this event yet. If you / your company would like to host this event, please contact the organizer.**</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1574092715000,
      duration: 7200000,
      id: '266557579',
      name: 'Le Wagon Talk with Fábio Oliveira (GetYourGuide)',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1580923800000,
      local_date: '2020-02-05',
      local_time: '18:30',
      updated: 1574092715000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      venue: {
        id: 26086918,
        name: 'Le Wagon Berlin Coding Bootcamp',
        lat: 52.50699996948242,
        lon: 13.39120101928711,
        repinned: true,
        address_1: 'Rudi-Dutschke-Straße 26',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1480930828000,
        name: 'Le Wagon Berlin - Coding Bootcamp',
        id: 21449749,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Le-Wagon-Berlin-Coding-Bootcamp',
        who: 'Members',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Le-Wagon-Berlin-Coding-Bootcamp/events/266557579/',
      description: '<p>⭐️⭐️⭐️ REGISTER VIA EVENTBRITE: <a >https://www.meetup.com/Le-Wagon-Berlin-Coding-Bootcamp/events/246861962/</a></p> <p>Like us on Facebook: <a >http://facebook.com/lewagonberlin</a></p> <p>Follow us on Twitter: twitter.com/lewagonberlin</p> <p>Look at some lovely photos on Instagram: <a >https://www.instagram.com/lewagonberlin/</a></p> <p>***************************************</p> <p>We look forward to meeting you soon!</p> <p>Team Le Wagon</p> ',
      how_to_find_us: 'Inside the courtyard, on the right, 5th floor, ',
      visibility: 'public',
      pro_is_email_shared: true,
      member_pay_fee: false
    },
    {
      created: 1563147324000,
      duration: 10800000,
      id: 'rdwzdryzqbtb',
      name: 'Drawin\'Togetha (zusammen Zeichnen) from/ab 16:30, Cafe Lentz (Mehringdamm)',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1576423800000,
      local_date: '2019-12-15',
      local_time: '16:30',
      updated: 1563147324000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 8,
      venue: {
        id: 25683300,
        name: 'Lentz Coffe ',
        lat: 52.4941291809082,
        lon: 13.38341999053955,
        repinned: true,
        address_1: 'Großbeerenstraße 27a, 10965',
        city: 'Berlin ',
        country: 'DE',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1543148829000,
        name: 'Late Sunday Afternoon Drawing (Sonntagszeichnenspätschicht)',
        id: 30590069,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Late-Sunday-Afternoon-Drawing-Meetup',
        who: 'Mitglieder',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Late-Sunday-Afternoon-Drawing-Meetup/events/rdwzdryzqbtb/',
      description: '<p>(If you prefer reading in English, please scroll down, below the German part!)</p> <p>-------------------------------------</p> <p>Hallo Ihr Lieben,</p> <p>Unsere Termine finden jeden Sonntag ab 16:30 Uhr im Café Lentz (Großbeerenstraße 27 a, 10965 Berlin, in der Nähe des U-Bahnhofs Mehringdamm) statt.</p> <p>Die Teilnahme am Meetup ist kostenlos und unverbindlich. Kein Zeichenkurs, kein Workshop, nur zusammen zeichnen. :-) Es gibt kein vorgegebens Programm, jeder benutzt Technik und Material nach eigenem Geschmack und wählt seine Inhalte selbst.</p> <p>Bring das eigene Material mit, um Deine Kreativität zu entfalten und, bitte, vergiss das Lächeln nicht: Wir sind alle da, um etwas Freies und Spontanes zu machen! Wir freuen uns auf Dich!</p> <p>Amateure und Profis sind willkommen, Anfänger wie Fortgeschrittene. Wir zeichnen/malen, quatschen ein wenig und schauen uns an, was die anderen gemacht haben.<br/>----<br/>About us:</p> <p>Out meetings happen every Sunday, from 4:30 PM in the Cafe Lentz (Großbeerenstraße 27 a, 10965 Berlin, not far from the underground station Mehringdamm).</p> <p>Participation to this meetup is free of charges. No drawing-class, no workshop whatsoever, just drawing together! :-) Every person choses their own material, technic and content.</p> <p>Bring your own material to let you creativity unfold and, please, don\'t forget to smile: we are all there to do something free and spontaneous! We can\'t wait to meet you!</p> <p>Amateurs and profis are welcomed, beginners and advanced. We sketch/draw/paint, talk a bit and look, what the others did.</p> <p>Stefan, in the footsteps of former organisator Alessandro</p> ',
      how_to_find_us: 'Vielleicht im Café, vielleicht draußen, erkennbar am Zeichenmaterial.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1545395196000,
      duration: 7200000,
      id: 'kpcqnqyzqbwb',
      name: 'APX Pitch Tuesdays',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1576598400000,
      local_date: '2019-12-17',
      local_time: '17:00',
      rsvp_close_offset: 'PT24H',
      updated: 1574945648000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 47,
      venue: {
        id: 26752780,
        name: 'moveBOX',
        lat: 52.507266998291016,
        lon: 13.394685745239258,
        repinned: false,
        address_1: 'Markgrafenstrasse 19a',
        address_2: 'Axel Springer Passage',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1542565400000,
        name: 'APX Axel Springer and Porsche - Berlin',
        id: 30551789,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'APX-Axel-Springer-and-Porsche-Berlin',
        who: 'Members',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/APX-Axel-Springer-and-Porsche-Berlin/events/kpcqnqyzqbwb/',
      description: '<p>*** This time, our pitch tuesday will TAKE PLACE AT moveBOX, Axel Springer Passage***</p> <p>Pitch Tuesdays is our weekly startup showcase, where APX portfolio founders will pitch for their ideas and the companies’ current status. This is an opportunity for them to excel in their public speaking skills and receive feedback from a public audience as part of the 100 days investor ready program.</p> <p>We often have visits from Master’s students, partners, investors, and employees from our shareholders: Axel Springer and Porsche. The best part? You can take part in it! This is valuable training for the APX portfolio founders, opportunities for our portfolio companies to gather insightful feedback, and also a great networking opportunity for you!</p> <p>Swing by our offices for a drink, see the pitches, and vote for your favourite.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1571642654000,
      duration: 25200000,
      id: 'hwsjkrybccbcc',
      name: 'Open Coworking im Kiez Büro an der Mall of Berlin',
      rsvp_limit: 5,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1579597200000,
      local_date: '2020-01-21',
      local_time: '10:00',
      updated: 1571642654000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 25770837,
        name: 'Kiez Büro An der Kolonnade',
        lat: 52.51190185546875,
        lon: 13.38132381439209,
        repinned: false,
        address_1: 'An der Kolonnade 11',
        city: 'Berlin',
        country: 'de',
        localized_country_name: 'Allemagne'
      },
      group: {
        created: 1517658875000,
        name: 'Kiez Büro Coworking Meetup',
        id: 27365336,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Kiez-Buro-Coworking-Meetup',
        who: 'Mitglieder',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Kiez-Buro-Coworking-Meetup/events/hwsjkrybccbcc/',
      description: '<p>Open Coworking im Kiez Büro an der Mall of Berlin: Laptop mitbringen und bei gutem Kaffee, Tee und ein wenig Frühstück entspannt arbeiten und andere Leute kennen lernen.</p> <p>Wir freuen uns auf viele neugierige Gäste!<br/>----------------------------------------------------------------------------------------------------<br/>Open Coworking at Kiez Büro an der Mall of Berlin: Bring your laptop and work relaxed with good coffee, tea and a little breakfast and get to know other people.</p> <p>We are looking forward to many curious guests!</p> ',
      how_to_find_us: 'Der Eingang ist auf der Ecke im Erdgeschoss',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1533891843000,
      duration: 10800000,
      id: 'gdsglrybccbmb',
      name: '67# Talk and socialize',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1578592800000,
      local_date: '2020-01-09',
      local_time: '19:00',
      updated: 1573992303000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      group: {
        created: 1372864747000,
        name: 'Elixir Berlin',
        id: 9199792,
        join_mode: 'open',
        lat: 52.52000045776367,
        lon: 13.380000114440918,
        urlname: 'Elixir-Berlin',
        who: 'Alchemists',
        localized_location: 'Berlin, Allemagne',
        state: '',
        country: 'de',
        region: 'fr_FR',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/fr-FR/Elixir-Berlin/events/gdsglrybccbmb/',
      description: '<p>👋 Hallo und herzlich Willkommen - we\'re back with the 67th edition of Elixir Berlin.</p> <p>⏰ Schedule</p> <p>6:45 PM: Doors open<br/>7:05 PM: Welcome &amp; Announcements<br/>7:15 PM: 🗣 TALK 1 by SPAKER ONE<br/>7:45 PM: 🍕Break 🍺<br/>8:00 PM: 🗣 TALK 2 by SPEAKER TWO<br/>8:30 PM: ⚡️ Lightning talks (Want to speak at this Meetup? Get in touch on GitHub*)<br/>8:45 PM: Socialize &amp; Chat about Elixir</p> <p>We want to encourage members of the Elixir community to share what they\'re working on. If you want to give a lightning talk at this Meetup, contact one of the organisers with a short description of your talk.</p> ',
      visibility: 'public',
      member_pay_fee: false
    }
  ]
};

export { mockEvents };